services:
  forefront-postgirl:
    build:
      context: .
      dockerfile: Dockerfile.production
      args:
        progress: plain
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    ports:
      - 6000:6000
    restart: on-failure:0
    networks:
      - web
networks:
  web:
    driver: bridge
