# Use the official Node.js image with a specific version
FROM node:18.17.0-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (if applicable)
COPY package*.json ./

# Install npm dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Set environment variables from .env.development
ENV $(cat .env.staging | xargs)

# Expose the port your app will run on
EXPOSE 8020

# Command to run your application
CMD ["node", "index.js"]
