services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      # The HTTP Port
      - "80:80"
      # The Traefik Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So Traefik can listen to Docker Events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

  forefront-postgirl:
    build:
      context: ../forefront-postgirl
      dockerfile: Dockerfile.production
      args:
        progress: plain
    environment:
      - NODE_ENV=production
    env_file:
      - ../forefront-postgirl/.env.production
    restart: on-failure:0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forefront-postgirl.rule=Host(`pintrail.app`) && PathPrefix(`/pg`)"
      - "traefik.http.services.forefront-postgirl.loadbalancer.server.port=6000"
    networks:
      - web
networks:
  web:
    driver: bridge
